# Generated by Django 5.1.6 on 2025-03-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_ordercounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='file_generated',
            field=models.BooleanField(default=False, help_text='Indicates if a file has been generated for this order'),
        ),
        migrations.AddField(
            model_name='order',
            name='file_generated_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the file was generated', null=True),
        ),
    ]
