# Generated by Django 5.1.6 on 2025-03-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_file_generated_order_file_generated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the order was delivered', null=True),
        ),
    ]
