# Generated by Django 5.1.6 on 2025-03-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='license_plate',
            field=models.CharField(blank=True, help_text='License Plate', max_length=50, null=True),
        ),
    ]
