# Generated by Django 5.1.6 on 2025-03-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_orderline_license_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='license_plate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
