# Generated by Django 5.1.6 on 2025-03-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_orderline_license_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='lot',
        ),
        migrations.AddField(
            model_name='orderline',
            name='lot',
            field=models.CharField(max_length=50, blank=True, null=True),
        ),
    ]