# Generated by Django 5.1.6 on 2025-03-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportdefinition',
            name='query',
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='query_file',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
