# Generated by Django 5.1.6 on 2025-03-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_reportdefinition_query_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportdefinition',
            name='query_file',
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='query',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
