# Generated by Django 5.1.6 on 2025-03-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_reportdefinition_query_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportdefinition',
            name='query',
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='file_path',
            field=models.CharField(default=1, help_text='Ruta relativa al archivo SQL', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='requires_project_filter',
            field=models.BooleanField(default=True, help_text='Si el reporte debe filtrarse por proyecto'),
        ),
    ]
